# Usage:
# Create a configuration file for your environment as instructed by the Readme.
# Replace (YOUR_CONFIG) occurences in this file to suit your config file name.

# @todo: Install OpenDuty by running the following commands
# - python manage.py syncdb
# - python manage.py migrate

app:
  image: pataquets/openduty
  command: python manage.py runserver
  environment:
    - DJANGO_SETTINGS_MODULE=(YOUR_CONFIG)
  links:
    - db
  ports:
    - 8080:8080
  volumes:
    - ./(YOUR_CONFIG).py:/usr/src/app/openduty/(YOUR_CONFIG).py:ro

db:
  image: mariadb:10.1
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=openduty
    - MYSQL_USER=openduty
    - MYSQL_PASSWORD=openduty
  volumes:
    - /data/openduty/:/var/lib/mysql
